### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by joanmarcfeina** [RaynaldM/autohelp#1]
Hello!

Can we have a tutorial on how to use it?

Thanks :)!

**Comment by Boorda** [comment]
Same question. How do I get it to read my assemblies?

**Comment by Boorda** [comment]
@joanmarcfeina I found this after posting here...
https://autohelp.codeplex.com/documentation

**Comment by RaynaldM** [comment]
Copy codeplex doc in github wiki
