### ISSUE TITLE
Cant acces to Manager or Connection view.

### ISSUE THREAD

**Issue by plecompt** [RaynaldM/autohelp#5]
Hi,

I deployed autohelp on IIS.
I can acces to the main view, but i can't acces to the Manage view or Connecting view.
Here are the screenshot of the errors.

[Manage View](https://ibb.co/mjBwOk)
[Connection View](https://ibb.co/m6nE9Q)
[Main View](https://ibb.co/kiDXw5)

I tried to add this two lines to fix the Connecting view, but it's not working.

`<add key="owin:AppStartup" value="AutoHelp.Startup, AutoHelp" />`
`<add key="owin:AutomaticAppStartup" value="true" />`

Thanks for help :)

**Comment by RaynaldM** [comment]
Autohelp use your windows account and AD if you want for connection.
Look my last commit

**Comment by plecompt** [comment]
Thx
